version: "3.7"
services:
  front:
    build: 
      context: .
      target: development
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true

  production:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  default:
    name: sed-network
    ipam:
      driver: default
      config:
        # 172.18 - по умолчанию, но пересекается с esd.rtech.ru
        - subnet: "172.16.238.0/24"